### PR TITLE
Fix bug where all events are unbound if no custom events provided.

### PR DESCRIPTION
**Pull request by RyanEwen**
Namespace event bindings and triggered events.
Add curly braces where missing.
Clear event bindings after settings are created, to allow clearing custom events properly (fixes bug where all events are unbound).

### CODE REVIEW

**Comment by RyanEwen** [comment]
Ping

**Comment by kaparelos** [comment]
Thank you Ryan 👍

**Comment by RyanEwen** [comment]
Actually this had some changes from my fork in it that are undesirable.. it changed the URL ref to your repo to my fork instead..

**Comment by kaparelos** [comment]
:(

**Comment by RyanEwen** [comment]
Just the readme file.. I suggest reverting that change if you can.

**Pull request merged**
